### ISSUE TITLE
how to setting Add table Head in left

### ISSUE THREAD

**Issue by cccfs** [liushuochen/gotable#2]
e.g:
+-----------+------+
|   China   |  Beijing  |
+-----------+------+
|    US        |  DC  |
+-----------+------+

**Comment by liushuochen** [comment]
Hi, This feature is not currently available. I will add this function in the new branch(master2.0)

**Comment by liushuochen** [comment]
Hi, The new feature which about align table headers & values had been merged in branch master2.0. You can refer to README.md on branch master2.0. If you have any questions, please contact me by email(shuochen2017@qq.com). Thanks for your feedback.
