### ISSUE TITLE
closeBorder后，最后一行会打印一行空行

### ISSUE THREAD

**Issue by YifangSun** [liushuochen/gotable#6]
最近发现 PrintTable 方法被弃用了。是出于什么考虑呢？

如果是gotable自己控制输出行为，可以在输出的时候判断一下，把最后一行换行符删掉

**Comment by liushuochen** [comment]
>>> 最近发现 PrintTable 方法被弃用了。是出于什么考虑呢？
>>> Hi, *Table实现了fmt.Stringer接口，因此使用fmt.Println(table)就可以直接打印出表格了。相关示例代码已在examples中做了更新。

>>> 如果是gotable自己控制输出行为，可以在输出的时候判断一下，把最后一行换行符删掉
>>> 这个需求我会放在下一个迭代版本中更新

**Comment by liushuochen** [comment]
Hi, 关于这个问题：“如果是gotable自己控制输出行为，可以在输出的时候判断一下，把最后一行换行符删掉“，在v5.4.0中已经解决。你可以使用table.End字段重新设置末尾的字符串。（默认情况下，table.End仍然是一个换行符'\n'，通过指定table.End = ""可以达到取消末尾空行的效果）。可以参考最新的示例代码。
